-- Seed: the "Cut my food spending" example vault.
DELETE FROM nodes WHERE vault_id='default';
DELETE FROM facets WHERE vault_id='default';
DELETE FROM edges WHERE vault_id='default';
DELETE FROM captures WHERE vault_id='default';
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','cook-club','seed','distilled','create','inherit','home','Make cooking a shared thing','Reframe from ''me cooking cheaply'' to ''a few of us cooking together'' — unlocks bulk without a car each.',0.68,'2026-07-18T09:12:00+07:00','What if cooking cheaply isn''t a solo chore but something a few neighbors do together?','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO facets (vault_id,node_id,name,semantic,distillate,confidence) VALUES ('default','cook-club','cost','accumulative','A group hits bulk pricing no one could alone — the same saving as the bulk store.',0.6);
INSERT INTO facets (vault_id,node_id,name,semantic,distillate,confidence) VALUES ('default','cook-club','access','gating','Someone has to organize the trip and the rota — the thing that makes or breaks it.',0.45);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cook-club',NULL,'split-batches',NULL,'sparks',NULL);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cook-club',NULL,'share-a-fridge',NULL,'sparks',NULL);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cook-club',NULL,'skill-swap-dinners',NULL,'sparks',NULL);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cook-club','access','no-bulk-access',NULL,'shares','the same transport blocker, now shared');
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','cook-more-home','hypothesis','distilled','solve','inherit','home','Cook most dinners at home','Home dinners could halve the eating-out line — if I can keep it up on busy nights.',0.6,'2026-07-18T09:12:00+07:00','Eating out is the leak. What if most weeknights were home-cooked instead?','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cook-more-home',NULL,'weeknight-system',NULL,'answers',NULL);
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','cut-food-spend','problem','distilled','solve','inherit','home','Cut my food spending by 30%','Eating out is the biggest leak; the fix is cooking more at home plus smarter shopping.',0.74,'2026-07-18T09:12:00+07:00','Where does the money actually go — groceries, eating out, or food that spoils?','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO facets (vault_id,node_id,name,semantic,distillate,confidence) VALUES ('default','cut-food-spend','cost','gating','Eating out is ~40% of the total — the number every option is judged against.',0.7);
INSERT INTO facets (vault_id,node_id,name,semantic,distillate,confidence) VALUES ('default','cut-food-spend','time','accumulative','Only ~4 hours a week to cook — the real constraint.',0.66);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cut-food-spend',NULL,'cook-more-home',NULL,'decomposes',NULL);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cut-food-spend',NULL,'smarter-shopping',NULL,'decomposes',NULL);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cut-food-spend','cost','cook-club','cost','shares','bulk pricing — two ways to get it');
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','cut-food-spend','time','smarter-shopping',NULL,'drives','the time limit pushes toward batch-shopping');
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','neighborhood-supper','synthesis','distilled','create','inherit','home','A neighborhood supper club','A few homes bulk-buy together, batch-cook, and split meals — cheaper food and less cooking for everyone.',0.61,'2026-07-18T09:12:00+07:00','The fusion: pool the shopping, share the cooking, split the meals — cheaper and less work than going it alone.','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','no-bulk-access','gap','distilled','solve','create','home','No easy way to buy in bulk','Flipped: the missing bulk access isn''t a wall — it''s the reason to team up with others.',0.5,'2026-07-18T09:12:00+07:00','The cheap bulk store is 40 minutes away and I have no car — bulk saving is real but I can''t reach it alone.

**Flipped.** Who else near me wants bulk groceries? What does sharing the trip unlock?','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','no-bulk-access',NULL,'weeknight-system',NULL,'blocks',NULL);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','no-bulk-access',NULL,'cook-club',NULL,'sparks',NULL);
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','share-a-fridge','seed','distilled','create','inherit','home','A shared bulk pantry','A small shared pantry lets a few homes buy in bulk and draw down as they need it.',0.52,'2026-07-18T09:12:00+07:00','Bulk only works if there''s somewhere to keep it. A shared pantry solves storage for everyone.','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','share-a-fridge',NULL,'neighborhood-supper',NULL,'combines',NULL);
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','skill-swap-dinners','seed','freeform','create','inherit','home','Trade dishes you''re good at',NULL,NULL,NULL,'Everyone can cook one thing well. Trade a portion of your specialty for someone else''s. Just a spark for now.','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','skill-swap-dinners',NULL,'neighborhood-supper',NULL,'combines',NULL);
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','smarter-shopping','hypothesis','distilled','solve','inherit','home','Shop with a list, buy staples in bulk','A fixed list kills impulse buys; bulk staples cut unit cost — needs discipline.',0.64,'2026-07-18T09:12:00+07:00','Impulse buys and small packs quietly add up. A list plus bulk staples fixes both.','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','smarter-shopping',NULL,'weeknight-system',NULL,'answers',NULL);
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','split-batches','seed','distilled','create','inherit','home','Cook double, split with a neighbor','One big cook feeds two homes for barely more effort — halves both cost and cooking time.',0.63,'2026-07-18T09:12:00+07:00','If I''m already batch-cooking, cooking double and splitting is almost free.','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO facets (vault_id,node_id,name,semantic,distillate,confidence) VALUES ('default','split-batches','effort','informational','One person cooks once instead of two people cooking twice.',0.55);
INSERT INTO edges (vault_id,src,from_facet,to_id,to_facet,rel,note) VALUES ('default','split-batches',NULL,'neighborhood-supper',NULL,'combines',NULL);
INSERT INTO nodes (vault_id,id,kind,state,region,lean,cluster,title,distillate_text,distillate_confidence,distillate_updated,body,created,updated) VALUES ('default','weeknight-system','solution','distilled','solve','inherit','home','Sunday batch-cook + a fixed grocery list','Batch-cook on Sundays and shop one strict list — clears the 30%, if I can buy in bulk.',0.62,'2026-07-18T09:12:00+07:00','Combine the two: cook once on Sunday, shop one disciplined list. What is still in the way?','2026-07-18','2026-07-18T09:12:00+07:00');
INSERT INTO captures (vault_id,id,text,created) VALUES ('default','c-leftovers','leftovers keep going bad — track them?','2026-07-18');
